### ISSUE TITLE
[Discussion] Feature based architecture + Styled-Components

### ISSUE THREAD

**Issue by harrisrobin** [infinitered/ignite-ir-boilerplate-andross#116]
Hello!

First off, used this boilerplate for a handful of projects and I am loving it. One thing though, I often find myself re-factoring the boilerplate a bit to work with a more feature based architecture that looks more like this:

Components
 -- {ComponentName}
    -- {ComponentName}.component.js
    -- {ComponentName}.redux.js

etc..

what are your thoughts on this? Wanted to get an idea before incase I go off and make my own boilerplate for this.

As a bonus, what are your thoughts on styled-components? This has also been working quite well for me in projects.

Cheers and thanks again for this awesomeness!

**Comment by jamonholmgren** [comment]
@harrisrobin I'm very sorry about the slow response time here! Glad you're liking our boilerplate!

I really like co-locating things like you've done.

We're currently working on a new file structure experiment. @skellock is driving that experiment forward in his latest project. I think it has similar characteristics to what you're proposing, although we haven't done a retrospective on the project yet.

`styled-components` is very cool. Another question for @skellock.

**Comment by skellock** [comment]
### structure

It feels much better grouping like this. Especially as the project grows.

I’ve landed on a new project organization that I’m loving. I gave the team an early preview a month or so ago. 

@leonskim and I are wrapping up a 2 month client project with this new structure now.

### styling libraries

`styled-components` and those types of libs are pretty good. I’ve tried most of them. I’ve found that they are much more useful on the web than in react native.

I’ve found that the `...spread` operator works great and you don’t have the mental overhead of another library.  That’s my opinion, I can see the use in them though! (Especially with dynamic themes)

### d.i.y. boilerplates

You should definitely do this. That’s one of core tenants of Ignite 2!

PS: I totally missed this issue as well, sorry. I read it but forgot to come back. I need to find a better system to keep up with github follow ups.

**Comment by georgevanderson** [comment]
@skellock Just ran across this thread and was considering doing the same re-factor to a feature based approach. When you say "feels much better grouping like _this_" did you mean the original or the feature based architecture. If the latter, do you think you'll be releasing a general overview of the new project organization. Thanks for all the work you've done, ignite is amazing!

**Comment by jamonholmgren** [comment]
Check out the latest boilerplate, [Bowser](https://github.com/infinitered/ignite-ir-boilerplate-bowser). Thank you!
