### ISSUE TITLE
Enzyme 3.0 Baby -- Let's Get This Back!

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-andross#119]
~Once #118 lands let’s delete all traces of `enzyme`.~

Oh snap!  Hold your horses!  Looks like Enzyme 3 is here now that React 16 landed.  Let's do some research and bring it back.

**Comment by Amurmurmur** [comment]
but how do we do tests than? something else is going to be used as a replacement for enzyme?

**Comment by skellock** [comment]
enzyme 3 shipped today... as did react 16.  once the fires subside we'll likely end up throwing this back in.   pretty much everyone here loved enzyme.
