### ISSUE TITLE
SectionLists as a set of flatlists?

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite-ir-boilerplate-andross#135]
https://github.com/facebook/react-native/issues/13192

Is this how multicolumn sectionlists should render???

**Comment by robinheinze** [comment]
This is how I did a multi-column section list in a recent project. It worked great. Maybe I should blog about it.

**Comment by nsalontay** [comment]
@robinheinze Do you have a sample you can share? I've been trying to adapt from that post, but no luck.

**Comment by robinheinze** [comment]
Hey @nsalontay! Yep, here's my example https://gist.github.com/robinheinze/19c4500b22a0c01d359f560d17612258. Hopefully it helps! 

This is what is should render:
![simulator screen shot - iphone 8 plus - 2018-01-25 at 09 21 36](https://user-images.githubusercontent.com/6894653/35402690-33fdea46-01b2-11e8-9002-39b0bda9ee1f.png)

**Comment by hagaigold** [comment]
```
  listContent: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    flexWrap: 'wrap'
  }
```

the SectionList style boilerplate have a "risky"  implementation as [point ](https://github.com/facebook/react-native/issues/13939#issuecomment-355700533) in facebook/react-native#13939
