### ISSUE TITLE
Please update 'redux-persist' dependency to v5

### ISSUE THREAD

**Issue by Jancat** [infinitered/ignite-ir-boilerplate-andross#162]
<https://github.com/rt2zz/redux-persist> 'redux-persist' has upgraded to v5 from v4, with some break changes to the boilerplate

**Comment by karlingen** [comment]
See https://github.com/infinitered/ignite-ir-boilerplate/issues/159

**Comment by Amurmurmur** [comment]
@GantMan Could you please check the pull request ? 👍 https://github.com/infinitered/ignite-redux-persist/pull/5
Hopefully guys at InfiniteRed can merge it as soon as possible 👍 
Thank you once again guys and the whole community, for such an awesome work done on this boilerplate 👍

**Comment by jamonholmgren** [comment]
Hey all, thanks for your patience! Several of us are out of town but will try to look at this as soon as we can.

**Comment by GantMan** [comment]
Bringing in @ryanlntn - who can hopefully help out while I'm unavail.

**Comment by ryanlntn** [comment]
Looking into this.
