### ISSUE TITLE
Missing android SDK 23

### ISSUE THREAD

**Issue by Slapbox** [infinitered/ignite-ir-boilerplate-andross#179]
I'm on Windows 7 x64 and having difficulty getting past this step. I've followed every guide I could find whether linked here or on Facebook's official documentation, but no luck at all. 

I've tried `Android Build Tools 23.0.1` and `23.0.3`, as well as later versions, but no luck with any options. I also tried ensuring that I only had one version of the build tools installed at a time and tried with each version, and no luck.

I believe my paths are set up correctly. Included in my `Path` variable are the following as I've seen advised in an issue thread I cannot find now, but this too did not help.
`D:\Android\sdk\platform-tools`
`D:\Android\sdk\build-tools`
`D:\Android\sdk\tools`

I'm using `Node 7.9.0` and `npm 4.2.0`

At the end of running the command `ignite new MyApp` I get the following:

```
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > failed to find Build Tools revision 23.0.3
      > failed to find Build Tools revision 23.0.3
```

Does anyone have any advice on how to remedy this? Thank you very much for reading.

**Comment by leonardo2204** [comment]
@Slapbox You probably don't have the build tools installed in your machine. Try opening the project from Android Studio (the android folder). It should prompt you to install the build tools, thus making this problem go away.

**Comment by jamonholmgren** [comment]
If this is still an issue, please feel free to comment. Thank you!
