### ISSUE TITLE
ignite-ir-boilerplate is not available on npm

### ISSUE THREAD

**Issue by soetedja** [infinitered/ignite-ir-boilerplate-andross#181]
I've installed the ignite-cli but when i try to create a new project, i get this error
🔥 igniting app MyNewAppName
× ignite-ir-boilerplate is not available on npm.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  We also searched in these directories:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Is there something I missed?

here's the output of ignite doctor

`F:\Research\ReactNative\ignite>ignite doctor
System
  platform           win32
  arch               x64
  cpu                4 cores                          Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
  directory          F:\Research\ReactNative\ignite

JavaScript
  node               7.6.0        C:\Program Files\nodejs\node.EXE
  npm                5.6.0        C:\Program Files\nodejs\npm.CMD
  yarn               0.17.6       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        C:\Users\usr\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\usr\AppData\Local\Android\sdk`

**Comment by adam-s** [comment]
Just run ignite without boilerplate name. It defaults to this one.

**Comment by pribeh** [comment]
The above doesn't work for me.

ignite doctor
System
  platform           darwin                                                                                
  arch               x64                                                                                   
  cpu                - cores                         ----  
  directory          /Users/name/Sites/projectname                                                        

JavaScript
  node               8.9.1        /usr/local/bin/node  
  npm                5.6.0        /usr/local/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_77     /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              7.3.1
