### ISSUE TITLE
bowser + react-native-keychain

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite-ir-boilerplate-andross#194]
Hey, I was just looking through the pre-release candidate for bowser and saw `react-native-keychain` added as a dependency. Is this is needed for every project?

I wrote an ignite plugin for react-native-keychain and I wondered how this might fit in to the new boilerplate (if at all).

**Comment by GantMan** [comment]
I think the first release might have it, and then maybe you and I work together to move it off to your plugin, which will detect Bowser vs Andross, and then add accordingly.

But version 1 of bowser will likely just show up with it in hand.  Once Bowser is out, let's chat in the slack on how to move forward.  👍 ?   

Also, most apps need keychain anyways right?

**Comment by juddey** [comment]
I'd imagine anything with authentication would. Others, not so much.

Sounds good! I'll make a note to ping you later if I haven't heard anything. It just works ™️ with Andross so its just a matter of sorting bowser.

**Comment by jamonholmgren** [comment]
@juddey Any updates on this?

**Comment by jamonholmgren** [comment]
@juddey Bowser does indeed ship with `react-native-keychain`. Any further thoughts at this point?

**Comment by juddey** [comment]
Are you thinking  `keychain` will be included in cyberdemon by default?
