### ISSUE TITLE
[Improvement] Native styles

### ISSUE THREAD

**Issue by AlirezaAkbarix** [infinitered/ignite-ir-boilerplate-andross#198]
I used to use ignite-v2 and now exploring on this amazing boilerplate and check new nice changes.
A thing that is so exciting for me is using preset widgets (`Button`, `Text`, ...), if you use native style e.g on `button` class it'll seem more awesome!
now for Android we haven't ripple effect and it behaves like iOS.
I'm sure you guys are perfect in react-native but for instance [THIS](https://medium.com/differential/better-cross-platform-react-native-components-cb8aadeba472) article helped me to make native buttons on my previous projects.

**Comment by jamonholmgren** [comment]
Thanks for the kind words @AlirezaAkbarix !
