### ISSUE TITLE
SwitchNavigator in react-navigation

### ISSUE THREAD

**Issue by darrenchiu** [infinitered/ignite-ir-boilerplate-andross#199]
Not sure if anyone raised this before. But it seems that the react-navigation included in the boilerplate is so old that it doesn't contain SwitchNavigator. What's the reason of keeping an old version of react-navigation and any suggestion for a replacement of SwitchNavigator?

Thanks a lot!

**Comment by jamonholmgren** [comment]
We're updated to React Navigation 3.0 now. Thanks!

https://github.com/infinitered/ignite-ir-boilerplate-andross/blob/923235692e5fb51a8e55e178e690b26793c214bb/boilerplate.js#L182
