### ISSUE TITLE
Old React-Navigation package

### ISSUE THREAD

**Issue by AlirezaAkbarix** [infinitered/ignite-ir-boilerplate-andross#200]
I've filed an issue on ignite-v2 ([This](https://github.com/infinitered/ignite/issues/1239)) about it and @GantMan said the future version (Bowser) fixes this problem. now I can see that `react-native` version is almost the latest version, but `react-navigation` version is still `1.0.0-alpha`!

**Comment by darrenchiu** [comment]
this is related to #199

**Comment by jamonholmgren** [comment]
Upgraded: https://github.com/infinitered/ignite-ir-boilerplate-andross/blob/923235692e5fb51a8e55e178e690b26793c214bb/boilerplate.js#L182

Thanks!
