### ISSUE TITLE
Cannot create project with Ignite

### ISSUE THREAD

**Issue by jetonk** [infinitered/ignite-ir-boilerplate-andross#211]
I try to create a project with Ignite, I'm getting these errors.

I'm using MacBook - macOS Sierra 10.13.5
NodeJS version: v8.9.4

----------
✖ ignite-ir-boilerplate-andross was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-andross --dev
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "Couldn't find package \"reactotron-core-client@^2.0.0-beta.6\" required by \"reactotron-redux@^2.0.0-alpha.3\" on the \"npm\" registry.".

----------
✖ ignite-vector-icons was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-vector-icons --dev
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "Couldn't find package \"reactotron-core-client@^2.0.0-beta.6\" required by \"reactotron-redux@^2.0.0-alpha.3\" on the \"npm\" registry.".

----------
✖ ignite-standard was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-standard --dev
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "Couldn't find package \"reactotron-core-client@^2.0.0-beta.6\" required by \"reactotron-redux@^2.0.0-alpha.3\" on the \"npm\" registry.".

----------

**Comment by skellock** [comment]
Wierd.  I just released `2.0.0-beta.6` of reactotron.  let me see what's up ehre.

**Comment by skellock** [comment]
Ok, this was my fault.  

Today, `lerna publish` didn't work.  It didn't publish everything.  It only published `reactotron-redux`.

I'm not quite sure what happened, but I just published all the dependencies manually.

Give that another shot and lemme know if it's still busted.

**Comment by jetonk** [comment]
Now I created the app, these errors do not appear.

**Comment by skellock** [comment]
Great, sorry about that.  I shouldn't be allowed near computers.
