### ISSUE TITLE
Can I just clone?

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite-ir-boilerplate-andross#213]
Hello! currently I cant seem to generate a whole ignite project using the `ignite new` command. Can I just clone the boilerplate?

**Comment by skellock** [comment]
`ignite new` performs important unpacking and setup steps.  

Can you share some details of the error you're seeing?

**Comment by mykelaballe** [comment]
I submitted an issue here https://github.com/infinitered/ignite/issues/1286. Its basically the same issue. the `ignite new` command does not generate project files, only empty folder and it seems nobody here knows the solution

**Comment by GantMan** [comment]
The boilerplate folder is the basics.  Just cloning  and copying those files over with renaming .ejs files should work.  It's far more manual that using the CLI though :(

@kevinvangelder - is our resident windows Guru

**Comment by mykelaballe** [comment]
@GantMan  thanks for the response. so you mean I can just rename .ejs files to .js?

![image](https://user-images.githubusercontent.com/22584900/41361696-44369f5c-6f62-11e8-85e5-faba9855ded9.png)

**Comment by mykelaballe** [comment]
is it possible you can send me a boilerplate with redux + react-navigation running a recent version of react-native?

**Comment by mykelaballe** [comment]
this is the boilerplate i'm using:

![image](https://user-images.githubusercontent.com/22584900/41362127-3065db5e-6f63-11e8-9780-844822c8cf2f.png)


![image](https://user-images.githubusercontent.com/22584900/41362173-4811e5fe-6f63-11e8-9e02-09e0f1fafb5b.png)

**Comment by GantMan** [comment]
rename the files, and you'll possibly need to remove any embedded JS as well.  Where we would inject the project name etc.

**Comment by mykelaballe** [comment]
why the Andross boilerplate https://github.com/infinitered/ignite-ir-boilerplate-andross doesnt have react-native in the dependencies?

![image](https://user-images.githubusercontent.com/22584900/41366314-44ce62b8-6f6e-11e8-9267-7a168ca23a96.png)

**Comment by GantMan** [comment]
you'd add these items to a living react-native project.  The CLI does a `react-native init` and then merges these libs.

**Comment by mykelaballe** [comment]
i got it working already. now I just need to add a drawer from DrawerNavigator
