### ISSUE TITLE
This template is great, but some library versions are low, so upgrade the dependency library, such as react-navigt-navigation-redux-helpers@2.0

### ISSUE THREAD

**Issue by fuxianwei** [infinitered/ignite-ir-boilerplate-andross#215]
This template is great, but some library versions are low, so upgrade the dependency library, such as react-navigt-navigation-redux-helpers@2.0

**Comment by tonmanayo** [comment]
this would be great

**Comment by jamonholmgren** [comment]
Just letting you all know this is on our radar. Expect more activity in a couple weeks.

**Comment by tonmanayo** [comment]
If you're interested I upgraded my boilerplate https://github.com/tonmanayo/react-native-startup

**Comment by jamonholmgren** [comment]
2.4.0 has upgraded dependencies, thank you!

**Comment by jamonholmgren** [comment]
@tonmanayo You should think about making that into an Ignite boilerplate. It's not difficult, and it would bring all the Ignite benefits. :)

**Comment by tonmanayo** [comment]
@jamonholmgren I'll have to update it again as we don't need to add react-navigation into redux anymore as of react-navigation v3
