### ISSUE TITLE
glog-0.3.4 error : 'config.h' file not found

### ISSUE THREAD

**Issue by khelil** [infinitered/ignite-ir-boilerplate-andross#224]
Hi All,

After creating an app from andross boilerplate, got a glog error : `node_modules/react-native/third-party/glog-0.3.4/src/base/mutex.h:105:10: 'config.h' file not found`

Here what i had to do to make it work : 

* Close Xcode.
* cd `node_modules/react-native/third-party/glog-0.3.4`
* Run `./configure`
* Run `make`
* Run `make install`
* Open Xcode and try building the Project.

Then i got a `libfishhook.a` error :

* select RCTWebSocket.xcodeproj
* select Build Phases
* delete libfishhook.a and reinstall it

Then got a `No member named __rip in __darwin_arm_thread_state` error

* Go to `node-module/react-native/third-party/glog-0.3.4/src/signalhandler.cc` and at line 78, and replace `return (void*)context->PC_FROM_UCONTEXT;` by `return NULL;`

Also, i have to follow theses steps every time i install a new react native lib :(

```System
  platform           darwin
  arch               x64
  cpu                4 cores                                                                                                    Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  directory         .../node_modules/react-native/third-party/glog-0.3.4

JavaScript
  node               11.1.0       /Users/khelil/.nvm/versions/node/v11.1.0/bin/node
  npm                6.4.1        /Users/khelil/.nvm/versions/node/v11.1.0/bin/npm
  yarn               1.12.3       /Users/khelil/.nvm/versions/node/v11.1.0/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.2        /Users/khelil/.nvm/versions/node/v11.1.0/bin/ignite

Android
  java               1.8.0_73     /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              10.1```

**Comment by jakesyl** [comment]
cd ./node_modules/react-native/third-party/glog-0.3.4 && ../../scripts/ios-configure-glog.sh

**Comment by jamonholmgren** [comment]
Anyone want to take a stab at upgrading to React Native 0.57.5? It should fix this issue with Xcode 10.

**Comment by khelil** [comment]
@jamonholmgren i'm in ! Can you give some indications ? 
I suppose we need to update Ignite CLI also ?

**Comment by jamonholmgren** [comment]
@khelil Apologies, I just saw this! Looks like @lvlrSajjad already got upgraded RN version out: https://github.com/infinitered/ignite-ir-boilerplate-andross/pull/228
