### ISSUE TITLE
Update React Native version to 57

### ISSUE THREAD

**Issue by darioajr** [infinitered/ignite-ir-boilerplate-andross#227]
Please update compatibility to react native version to last version 57.

**Comment by jamonholmgren** [comment]
Hey @darioajr! Andross is in its "Community Support" phase, so while we're super happy to test and merge pull requests, Infinite Red won't be updating it ourselves. Want to take a crack at this?

**Comment by darioajr** [comment]
my package.json file:
`{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "clean": "rimraf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
    "clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
    "newclear": "rimraf $TMPDIR/react-* && watchman watch-del-all && rimraf ios/build && rimraf node_modules/ && npm cache clean --force && npm i",
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "android:build": "cd android && ./gradlew assembleRelease",
    "android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
    "android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
    "android:devices": "$ANDROID_HOME/platform-tools/adb devices",
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
    "precommit": "npm run git-hook",
    "prepush": "npm run git-hook",
    "git-hook": "npm run lint -s && npm run test -s",
    "storybook": "storybook start -p 7007",
    "lint": "standard --verbose | snazzy",
    "lintdiff": "git diff --name-only --cached --relative | grep '\\.js$' | xargs standard | snazzy",
    "fixcode": "standard --fix"
  },
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "antd-mobile": "^2.2.3",
    "antd-mobile-rn": "^2.2.1",
    "apisauce": "0.14.3",
    "appcenter": "^1.8.1",
    "appcenter-analytics": "^1.8.1",
    "appcenter-crashes": "^1.8.1",
    "appcenter-push": "^1.8.0",
    "base64-js": "^1.3.0",
    "firebase-messaging": "^1.0.6",
    "format-json": "1.0.3",
    "i18n-js": "3.0.11",
    "identity-obj-proxy": "3.0.0",
    "immutability-helper": "^2.8.1",
    "lodash": "4.17.5",
    "moment": "^2.22.2",
    "native-base": "^2.8.0",
    "net": "1.0.2",
    "npm": "^6.3.0",
    "prop-types": "15.6.0",
    "querystringify": "1.0.0",
    "ramda": "0.25.0",
    "react": "16.6.1",
    "react-fast-compare": "^2.0.3",
    "react-jhipster": "^0.5.8",
    "react-native": "0.57.5",
    "react-native-animatable": "^1.3.0",
    "react-native-autocomplete-input": "^3.6.0",
    "react-native-calendars": "^1.20.0",
    "react-native-camera": "^1.3.0",
    "react-native-config": "0.11.5",
    "react-native-device-info": "0.11.0",
    "react-native-git-upgrade": "^0.2.7",
    "react-native-image-gallery": "^2.1.5",
    "react-native-indicator": "^0.7.0",
    "react-native-keyboard-aware-scroll-view": "0.4.4",
    "react-native-languages": "^3.0.0",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-router-flux": "4.0.0-beta.28",
    "react-native-vector-icons": "5.0.0",
    "react-navigation": "2.17.0",
    "react-redux": "5.0.7",
    "realm": "^2.14.0",
    "redux": "3.7.2",
    "redux-persist": "5.9.1",
    "redux-saga": "0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "7.1.3",
    "sockjs-client": "https://github.com/sockjs/sockjs-client#4d18fd56a6c4fb476c3e1931543a6cb9daaa6eba",
    "stompjs": "2.3.3",
    "tcomb-form-native": "0.6.11",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@storybook/addon-storyshots": "3.3.15",
    "@storybook/addons": "3.3.15",
    "@storybook/channels": "3.3.15",
    "@storybook/react-native": "3.3.15",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "23.4.2",
    "babel-plugin-ignite-ignore-reactotron": "0.3.0",
    "babel-plugin-import": "^1.8.0",
    "babel-preset-env": "1.6.1",
    "buffer": "5.1.0",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "1.1.1",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.2.1",
    "ignite-animatable": "^1.0.0",
    "ignite-dev-screens": "^2.3.0",
    "ignite-i18n": "^1.1.1",
    "ignite-ir-boilerplate": "^2.3.3",
    "ignite-jhipster": "^1.10.3",
    "ignite-standard": "^1.0.0",
    "ignite-vector-icons": "^1.1.0",
    "jest": "22.4.2",
    "metro-react-native-babel-preset": "^0.49.2",
    "mockery": "2.1.0",
    "react-dom": "16.3.0-alpha.1",
    "react-test-renderer": "16.3.0-alpha.1",
    "reactotron-react-native": "2.1.0",
    "reactotron-redux": "2.1.0",
    "reactotron-redux-saga": "2.1.0",
    "rimraf": "2.6.2",
    "snazzy": "^8.0.0",
    "standard": "^12.0.1"
  },
  "jest": {
    "testMatch": [
      "**/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "Tests/Setup.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
    "setupFiles": [
      "./Tests/Setup",
      "<rootDir>/node_modules/appcenter/test/AppCenterMock.js",
      "<rootDir>/node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js",
      "<rootDir>/node_modules/appcenter-crashes/test/AppCenterCrashesMock.js",
      "<rootDir>/node_modules/appcenter-push/test/AppCenterPushMock.js"
    ],
    "coveragePathIgnorePatterns": [
      "App/Services/Api.js",
      "App/Themes/",
      "/storybook/",
      "/*\\.story\\.js"
    ],
    "preset": "react-native"
  },
  "config": {},
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "test",
      "jest",
      "expect",
      "fetch",
      "navigator",
      "__DEV__",
      "XMLHttpRequest",
      "FormData",
      "React$Element"
    ],
    "ignore": [
      "ignite/**"
    ]
  }
}
`

**Comment by clive107** [comment]
@darioajr Thanks. I managed to make it works now. My package.json follows the bowser boilerplate (for babel and jest related packages, but I didn't include the jest-preset-ignite). I changed my .babelrc to babel.config.js to make it works.

**Comment by jamonholmgren** [comment]
Fixed by https://github.com/infinitered/ignite-ir-boilerplate-andross/pull/228
