### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by cwagner22** [infinitered/ignite-ir-boilerplate-andross#71]
How can I access the components from `ignite/Examples/Containers/ignite-ir-boilerplate` (SectionExample.js etc) directly from the dev screens? Also it looks like the sagas examples are missing as well.
Why the boilerplate has much less examples than ignite v1?

**Comment by GantMan** [comment]
Hiya @cwagner22 -  Please pardon us as we clean up.  We're hoping to move some of those examples to plugins.  Like `ignite add loginscreen` or something nice like that.  So it can grow without adding bulk to the base project.  

Perhaps you'd like to take a stab at taking our saga example and making a plugin?   It's actually quite easy, we're just very focussed on making sure "plugins" work correctly at this time, and it's holding us back from writing them!!!   Any help would be ❤️

**Comment by cwagner22** [comment]
I see, I guess I could take a look if nobody else if working on it. So I just have to follow [this doc](https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md) and add the login saga?

**Comment by GantMan** [comment]
Basically, yes.   This helps us get more compose-able pieces which is the goal of 2.0.

Additionally, I'll add this:  If you get stuck, or find any issues in our docs please let us know.  We really want to make the plugin architecture top-notch right now, so *everyone* can build plugins that benefit everyone.
