### ISSUE TITLE
Npm install any module results in react-native is missing?

### ISSUE THREAD

**Issue by maitham1** [infinitered/ignite-ir-boilerplate-andross#83]
Hey, 

Awesome stuff with ignite guys. I'm new to ignite and react and after installing the boilerplate, i'm trying to add firebase to the project by running npm install firebase. However, regardless of what I install it seems like all the modules in node_modules are no longer recognized. I then have to reinstall every module again by specifying npm install "module Name". I can't work out why this is happening ? Can anyone help ?

**Comment by skellock** [comment]
Where are you seeing this error?  Are you running the right packager? Can you show me your `ignite doctor`?

**Comment by jbreuer95** [comment]
@maitham1 i had this problem too yesterday, i updated my npm and it all worked like expected again.

**Comment by jamonholmgren** [comment]
@maitham1 Can you update node / npm and see if it still has some issues? Also post `ignite doctor` results here.

**Comment by HelloEdit** [comment]
One of the best solutions in the long term is to work with [Yarn](https://yarnpkg.com/lang/en/docs/install/). 
Theoretically, the problem should no longer occur 😄
