### ISSUE TITLE
Plans for globalizing actions via bindActionCreators?

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite-ir-boilerplate-andross#86]
I've seen the redux pattern in other projects where mapDispatchToProps is bound to all action creators through bindActionCreators... That way, it's one less thing to define in each container. For example, we'd add to a container:

```
import { bindActionCreators } from 'redux';
import { ActionCreators } from '../Redux';

const mapDispatchToProps = (dispatch) => {
    return bindActionCreators(ActionCreators,dispatch);
}
```

And Redux/index.js would also have (as an example): 

```
import ProductActions from './ProductRedux'
import BusinessActions from './BusinessRedux'

export const ActionCreators = Object.assign({}, // This needs to be defined
  ProductActions,
  BusinessActions
)
```

Each reducer already exports Creators extracted from createActions(), so it seems logical to take that one step further.

**Comment by jamonholmgren** [comment]
This is a cool idea but we don't plan to add this feature to Andross now that we are working primarily on [Bowser](https://github.com/infinitered/ignite-ir-boilerplate-bowser). Thank you!
